//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Denuncias
    {
        public int IdDenuncia { get; set; }
        public int IdPedido { get; set; }
        public Nullable<int> IdEstado { get; set; }
        public string DescripcionPedido { get; set; }
        public string Motivo { get; set; }
    
        public virtual Pedidos Pedidos { get; set; }
    }
}
