//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Postulaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Postulaciones()
        {
            this.Notificaciones = new HashSet<Notificaciones>();
        }
    
        public int IdPostulacion { get; set; }
        public int IdTipoActividad { get; set; }
        public int IdPedido { get; set; }
        public string IdUsuarioPostulado { get; set; }
        public int IdEstadoPostulacion { get; set; }
        public double TiempoEstimado { get; set; }
        public decimal Precio { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Estados Estados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notificaciones> Notificaciones { get; set; }
        public virtual Pedidos Pedidos { get; set; }
        public virtual TiposActividades TiposActividades { get; set; }
    }
}
