//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Postulaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Postulaciones()
        {
            this.Notificaciones = new HashSet<Notificaciones>();
        }
    
        public int IdPostulacion { get; set; }
        public int IdTipoActividad { get; set; }
        public int IdPedido { get; set; }
        public string IdUsuarioPostulado { get; set; }
        public int IdEstadoPostulacion { get; set; }
        public double TiempoEstimado { get; set; }
        public decimal Precio { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Estados Estados { get; set; }
        public virtual TiposActividades TiposActividades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notificaciones> Notificaciones { get; set; }
        public virtual Pedidos Pedidos { get; set; }
    }
}
